name: 'New Relic Application Deployment Marker'
author: 'New Relic'
description: 'Apply a New Relic application deployment marker to an application that is monitored by New Relic.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  apiKey:
    description: 'Your New Relic User API Key.'
    required: true
  accountId:
    description: 'Your New Relic account ID. This account ID should have access to the specified application.'
    required: true
  applicationId:
    description: 'The application ID to apply the deployment marker.'
    required: true
  revision:
    description: 'Custom revision information to add to the deployment marker - e.g. the latest tag.'
    required: true
  region:
    description: 'The geographical region for your New Relic account - US or EU. Default: US'
    required: false
    default: US
  description:
    description: 'Description stored with the deployment. Default: <none>'
    required: false
  changelog:
    description: 'Change log string stored with the deployment. Default: <none>'
    required: false
  user:
    description: 'The user creating the deployment. Default: `github.actor`'
    required: false
    default: '${{ github.actor }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    NEW_RELIC_API_KEY: ${{ inputs.apiKey }}
    NEW_RELIC_ACCOUNT_ID: ${{ inputs.accountId }}
    NEW_RELIC_APPLICATION_ID: ${{ inputs.applicationId }}
    NEW_RELIC_REGION: ${{ inputs.region }}
    NEW_RELIC_DEPLOYMENT_USER: ${{ inputs.user }}
    NEW_RELIC_DEPLOYMENT_REVISION: ${{ inputs.revision }}
    NEW_RELIC_DEPLOYMENT_CHANGE_LOG: ${{ inputs.changelog }}
    NEW_RELIC_DEPLOYMENT_DESCRIPTION: ${{ inputs.description }}
